/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        'text': '#D4D4D4',
        'rgb-text': 'rgb(212,212,212)',
        'subtext': '#D4D4D4',
        'rgb-subtext': 'rgb(212,212,212)',
        'main': '#0A0A10',
        'rgb-main': 'rgb(10,10,16)',
        'main-transition': '#0A0A10',
        'rgb-main-transition': 'rgb(10,10,16)',
        'highlight': '#191923',
        'rgb-highlight': 'rgb(25,25,35)',
        'highlight-elevated': '#0d0d14',
        'rgb-highlight-elevated': 'rgb(13,13,20)',
        'sidebar': '#0A0A10',
        'rgb-sidebar': 'rgb(10,10,16)',
        'player': '#0A0A10',
        'rgb-player': 'rgb(10,10,16)',
        'card': '#191923',
        'rgb-card': 'rgb(25,25,35)',
        'shadow': '#AF8BF3',
        'rgb-shadow': 'rgb(175,139,243)',
        'selected-row': '#353447',
        'rgb-selected-row': 'rgb(53,52,71)',
        'button': '#D4D4D4',
        'rgb-button': 'rgb(212,212,212)',
        'button-active': '#353447',
        'rgb-button-active': 'rgb(53,52,71)',
        'button-disabled': '#111117',
        'rgb-button-disabled': 'rgb(17,17,23)',
        'tab-active': '#191923',
        'rgb-tab-active': 'rgb(25,25,35)',
        'notification': '#0A0A10',
        'rgb-notification': 'rgb(10,10,16)',
        'notification-error': '#F7407B',
        'rgb-notification-error': 'rgb(247,64,123)',
        'misc': '#0A0A10',
        'rgb-misc': 'rgb(10,10,16)',
        'play-button': '#2B2A3D',
        'rgb-play-button': 'rgb(43,42,61)',
        'play-button-active': '#353447',
        'rgb-play-button-active': 'rgb(53,52,71)',
        'progress-fg': '#F7407B',
        'rgb-progress-fg': 'rgb(247,64,123)',
        'progress-bg': '#0A0A10',
        'rgb-progress-bg': 'rgb(10,10,16)',
        'heart': '#F7407B',
        'rgb-heart': 'rgb(247,64,123)',
        'liked-left': '#0A0A10',
        'rgb-liked-left': 'rgb(10,10,16)',
        'liked-right': '#ffffff',
        'rgb-liked-right': 'rgb(255,255,255)',
        'pagelink-active': '#F7407B',
        'rgb-pagelink-active': 'rgb(247,64,123)',
        'radio-btn-active': '#191923',
        'rgb-radio-btn-active': 'rgb(25,25,35)'
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}